### ISSUE TITLE
Ruth RC#4 Preparation

### ISSUE THREAD

**Issue by aiaustin** [RuthAndRoth/Ruth#14]
This issue is for discussion of the contents and preparation of RC#4 to document what may be included and decisions taken where there has been any debate.

**Comment by aiaustin** [comment]
My own suggestions are as follows...

1. That we fully document the whole process to build and create the release for both Second Life and OpenSim, including version numbers of all tools used and parameter settings for Blender exports to Collada/DAE, import settings to SL and OpenSim, etc.

2. We include all parts for body, feet and hands, head, root prim and HUDs.

3. We preserve the specific DAE made so there is a single common base for this.

4. We ensure all textures for the body parts and HUDs are available in GitHub and included in the master in world distribution separately.

5. For the skins, we also ensure they are on GitHub. We can refer to other skins, buts lets keep the core release fully open source available. Again these should be available in the master inworld separately.

6. It would be nice to include the skins in Shin Ingen's original skin applier HUD with dragon tattoo and non-tattooed versions to credit back to his kicking off the project.

7. For the HUDs I have a preference for the slate grey background variant we have mad from Shin's Ruth 2.0 RC#1 to RC#3 and Roth 2.0 RC#1 versions. Sean's bright red is a bit strong (for me). That colour also let's Sean differentiate his modified versions clearly. I would drop the dragon background on the HUDs though going forward.

8. Script details and how to build and modify then, how to add new skins, how to make a skin coloured attachment (like the Elf Ears) work, etc should be included.

9. For the final version in Second Life and OpenSim make available a single source in world for all assets so there is a common shared UUID for each asset and texture, to improve efficiency and reuse/faster loading where multiple Ruths and Roths are inworld together. Create an IAR for the OpenSim master asset “box”.

**Comment by seriesumei** [comment]
Thank you for kicking this off Austin!

5. I've been using Linda Kellie skins for now since the licensing on those is clear and they are available from well-known places.  I am wondering if some of the things currently in this repo should be moved to a separate one because they are used differently or have different release cycles? (Austin and I have talked about this a bit already).  A skin repo would be something that would not change regularly, mostly just have new textures added, and might be easy to do this with.  We could leave a couple in the main repo as 'references'.

6. Totally!  I recall looking for those in Github and not being sure I found them, are they in the repo now?  I'll go look again later today.

7. I am with you on the colors and can go either way on dropping the dragon in the background, if we do that I'd suggest a slight gradient as totally flat can look, well, flat. :). But that's a detail.  Is there a desire to use my combination HUD as the main one going forward?  It doesn't hurt my feelings if not, I will finish and distribute it either way.   Creating the HUD itself in-world is still awkward but most of it is scripted now.  If we want to use it I'll wrap it up and propose it for the main directories and people with actual design skills can help make it beautiful :)

8. I've nearly finished the notecard loading version for skins that can also work as a stand-alone applier and optionally include Omega targets. I think to start at least we shouldn't try to make the default skin HUD do everything you would want, but be a good base, as some things by nature will work better in smaller packages.   But then I am used to the common practice in SL of individual appliers for makeup, tattoos, freckles, etc. and the body HUD basically only having skin tones.

9. I've been keeping a box in my store that has the direct mesh uploads to keep track of what I've used.  I believe this re-enforces the spirit of GPL licenses (we meet the requirements with the files in Github) by having them readily available for others in-world.  Is there already a group to hold the ownership of 'release components' and whatnot?

**Comment by aiaustin** [comment]
I am a +1 on using your scripts as a base Serie. Reminder: that I could not work out how to set up the Elf Ears with your script setup. We used to just drop in the previous r2 head receiver script along with making the object description “head”... ditto for tails using the r2 body receiver script and description “lower”. We need to document how people make body coloured/textured attachments.

I personally am okay with several HUDs rather than one ginormous one that is extremely large with lots of textures. Especially to separate less frequently used functions from ones changed in regular use.

Good idea on the slate grey with a gradient as a background for the HUDs.. incorporating the small R2 in a circle as the logo where appropriate.

Good point about group. There is the RuthandRoth group in SL.. maybe we should get one set up in OpenSim (OSGrid?) too.

**Comment by AdaRadius** [comment]
Thank you Austin! (Do we call you Ai or Austin?)
1. I am gathering whatever I can find from contributors since RC3 and am working on them. I'll upload blend files (maybe three blend files - modeling//UVweighting, alpha cut proposals and normal/spec maps), dae files, and document within the Blender files the source files and version numbers of the software I'm using. 
2. Change the organization at GitHub? Folders for uploadable dae and HUD assets seems reasonable: RothRC2, RuthRC4, etc. 
3. I'm not sure what you mean by this.
4. We have a folder for skin textures at GitHub, that can be used on any version of the bodies. Do we need more than this? Textures for the HUDS should change for each RC, of course - maybe put them in with the HUD assets for each RC version?
5. All of the skins that are open source, or CC or whatever free licensing can be uploaded to GitHub, sure. Fred already has many at his website, so I think that's somewhat redundant. 
6. Sure. I think, more important, is a good list of contributors on a texture and in a text file inworld. I'm listing the contributors for modeling, UV and vertex weighting in the Ruth RC4 blend files (and will do the same for RothRC2, but I don't know who has done what for HUDS and any other scripting. We have a lot of volunteers putting many hours into this, they need to be highly praised whenever possible. 
9. Where inworld? I can maybe offer a long-term location - New Media Arts, Inc. (a 501(c)(3) nonprofit) maintains sims at Kitely - I can ask the board (I'm the founder, was once on the board, and may be again) if we can use space on Cookie II, or for some budget for a Ruth/Roth world. They're already hosting and maintaining the most complete Arcadia Asylum/Aley collection and host Community Virtual Libraries, and websites for more - virtual and online libraries is the core of their mission. Kitely is running a different OS version than most of the rest of OS, so Ruth&Roth would need another location running the bleeding edge version, so we can test compatibility. I'm never in SL, it gets too expensive to upload and maintain stuff there.    
10. An issue I get asked about a lot - licensing. I can't figure out from the GitHub files which pieces are licensed how and who can do what with which.  That needs some work.  Who knows enough to sort it out?

**Comment by aiaustin** [comment]
OpenSim OSGrid group with name "RuthAndRoth" (to match the GitHub group name) created.

Second Life holder for group name "RuthAndRoth" (to match the GitHub group name) also created. But note on it that its best to use Hyacinth's existing "Ruth and Roth Community" group which already is being used.

**Comment by aiaustin** [comment]
Ai here Ada :-)

**Comment by aiaustin** [comment]
Fred is our licensing man and is the best to check any issues out with. Shin Ingen wanted to use AGP for the core, so that's essential now and not changeable for the core.  Some other folks (like me) like CC-BY or CC-BY-NC.

I agree we don't need to repeat things that are already in repositories or accessible elsewhere... like lots of alternative skins. But a few of the things we directly include in the releases and all the skins and textures for that ought to be here for permanence.  Repositories and web sites do disappear over time.

For a permanent location, Kitely is a bit problematic, as the folks there have said they might not allow Ruth 2.0 and Roth 2.0 because of the licensing as AGPL. They maye be more relaxed now its in more widespread usage, but there was a bit of discussion with Ilan Tochner on this.

**Comment by AdaRadius** [comment]
Thank you Ai! 
Ya, I was the back end channel on the 'discussion' between Shin and Ilan. Shin was emphasizing that this is a teaching project, and that's my objective as well, which is one reason why I'm suggesting one of the New Media Arts worlds as a long term solution - another reason is that they're more likely to be around for longer than an individual's server.  

I'll talk to Ilan. He is now working with educators on a new Kitely service, so his business objectives may have changed.  I agree, one of the CC flavors is more adaptable to our various objectives, and that's what Ilan was asking for. 

Can I assume that the core models are AGP, but the HUDS, feet, fingernails, toenails, animations and textures might be CC? UV maps and vertex weighting are more-or-less integral to the models, so they'd be AGP. Probably.  

I know that the clothing designers would like to be able to include the Ruth or Roth models and customized HUDS  with the clothing, and that Kitely Marketplace is set up (a work in process) to make it easier to list required attributions. No marketplace allows links to other sources within product descriptions, but Ilan has suggested putting that information into a text file with the items for sale. What I don't know is if that's allowed under AGP.

**Comment by aiaustin** [comment]
Ada, Fred might comment, but what you suggest I believe is compatible with the objectives that Shin had for the core body and any refinement or development of it. That just also has to be AGPL and available somewhere for free. Add ons and skins, etc can use the license that the developer wishes, and can use CC, be commercial, etc. And I believe anyone can include the AGPL parts (core body, etc.) and parts under other licences which allow it with their packaged open source and commercial releases. Using a notecard to describe the sources, credit developers, give license details, and give links to where to obtain refined versions of any AGPL parts makes sense. I always include a Read Me file with packages.

**Comment by seriesumei** [comment]
re licensing: My day job is in Open Source development, my understanding from our project experts is that CC-* licenses are useful for documentation and non-code things while *GPL (and variants) and the permissive licenses (Apache, BSD, MIT, etc) are better for code.  I think Blender files are considered data so I'm unsure if one is better than the other.  as nor exactly how the *GPL license linking issues affect things like mesh.  I suspect that we are OK here as long as the license mixing is compatible, what I have seen so far is. (i.e., the project default is AGPL but including Apache/BSD/MIT or CC-* is OK; the opposite is not in most cases).  I would be willing to re-license my scripts in a non-GPL form is someone is nervous about that.  I like the GPL philosophically but pragmatically live in an Apache world most of the time.

Re the group in SL: I am fine to use whatever group makes sense.  Most of my concern is that we make sure to guard against the single-point-of-failure like we had with Shin's Github repo.  That has been taken care of with the new repo, I think doing something similar for the 'owner' of the in-world 'master' copy of things makes sense too.  I have room in my SL store to keep stuff, need to go get set up in Kitely it seems (the little free parcel I had in OSGrid vanished last month :( ).

**Comment by aiaustin** [comment]
Fred Beckhusen provided some notes... 30-Mar-2019:

I've been following  the emails about the license, it's pretty much what the email chains say.   Shin and I picked AGPL to keep the body from being modded and making the changes exclusive to your server, without passing it on.

I agree that anyone can add any accessories and license those as you wish so long it does not contain the AGPL bits.

Anything  that was uploaded without a license is automatically AGPL. Only the original author of that can change the license to something else.  Any copies out there before it changes remain AGPL.

For example, assume someone loaded an unlicensed toenail. It's automatically AGPL.  The author changes his mind and changes the license to CC-BY.  Its now CC-BY, but prior versions or copies are still AGPL.  One exception:  CC-0 means no license.  CC-0 is unusual in that anyone can mod that toenail like AGPL, sell it ( like AGPL) , even re-license it ( unlike any other license), then mod it without sharing the changes back (unlike AGPL).   AGPL is the only license that prevents people from modding it, running it on their private server,  and not giving the mods back to the community.  Specifically, grid owners who want to use modified Ruths as starter avatars.

**Comment by AdaRadius** [comment]
OK. To make sure I understand this: The core model has been a team effort and there have been many changes to Shin's original ZBrush model to make it work for UV mapping to the legacy skins and vertex weighting to the SL/OS armatures, though its general appearance is still distinctively Shin's. AGPL, and we provide a link to this GitHub in the ReadMe, no matter how we distribute it, along with a link to the license itself.  The fingernails, toenails, animations, HUDS and programming are also very much team efforts, generally with one originator, and are CC-BY if specified, and AGPL if not?

**Comment by aiaustin** [comment]
If I understand this correctly you are not quite right,.  The HUDs as originally released are also AGPL aren't they.  they do contain the AGPL "dolly" 3D avatar model anyway so I would assume so. But after a long discussion on GitHub and the Google+ Community pages it was agreed that CONTENTS could be added into HUDs (such as skins and textures, etc) that were licensed according to what the creator of that add in content wanted. All other parts can be licensed as the author(s)/creator(s) wish.

I am interpreting what I understand of the discussion here related to the AGPL basis of Ruth and Roth.  I have not myself ever used AGPL for open source developments. I have wanted very widespread use and adaptation (free and otherwise). So, I have always used Lesser GPL and more recently and CC-BY (or CC-BY-NC in a few cases where elements needed to be kept free).

**Comment by AdaRadius** [comment]
And back to the main topic of this GitHub issue:
I am working in Ruth2.0_RC#4b.blend, which I expect to bring inworld today for preliminary testing. I took assets from these sources and contributors and further (I hope) improved vertex weighting and UV mapping, making minor changes to the model where needed to get the thing working with the legacy skins and SL/OS armatures:
From Release3_AdaShinEdit_SundanceEdit_16.blend - fingernails and UV last worked on by Sundance Haiku. Model by Shin Ingen. Skinning and vertex weighting by Ada Radius

Appended feet from OSRuth2_CurrentRelease_DEVKIT_CURIOUS_TAARNA_r2FEET_RC#3.blend - medium height foot, UV mapping

Appended feet from OSRuth2_02Ada2.1Feet.blend - labeled "posable" - weighted to more bones with the pose library for foot poses at a range of heel heights. . 

Appended body and hands from OSRuth2_02Ada1.8_UV58.blend - Leona Morro UV mapping

CONTRIBUTORS TO THIS FILE: 
Shin Ingen - modeling, vertex weighting
Ada Radius - vertex weighting, modeling, UV mapping, foot poses
Sundance Haiku - UV mapping, modeling
Curious Creator - UV mapping?
Taarna Welles - UV mapping
Leona Morro - UV mapping
Eloh Eliot - Starlight skin textures
Robin Wood - templates 
Chip Midnight - templates

Software: ZBrush (original model by Shin Ingen), Blender V2.79b with Avastar Bento plugin v.2.5.18 - materials, UV mapping, vertex weighting, animations.  

Note: there's an "a" and "b" version of this file - the "a" version has more draft copies and shows the workflow better, but it got corrupted, which happens often while working with simulation of the inworld sliders on the collision volume armature. For the 'b' version I opened a clean file, added a clean armature, and appended just the assets I'll need for uploading, and finished this draft.

**Comment by seriesumei** [comment]
I think that is very close Ada; if all authors of a particular thing agree, it can be licensed however they wish, ie, it need not be specifically CC-BY.

I'll do a bit of checking, I think we have some things in the repo that need cleaning or clarifying license-wise.

**Comment by AdaRadius** [comment]
Thank you Serie! It will be good when we can provide language for addon designers to use so that the licensing and attributions survive. The ManuelBastioni plugin does that for its avatars - pretty much saying: copy and paste this into your readme and you'll satisfy my licensing requirements. We already have a culture of doing that in SL scripting - attributions stacked into the // lines for each contributor, and I think most people will be happy to do it. If it's easy.

**Comment by AdaRadius** [comment]
@Ai re HUDS and AGPL: OK, so that needs to be described differently. 
@Fred: Is there a draft somewhere of the correct language that could be cut down to be simple enough for the artists to use?

**Comment by AdaRadius** [comment]
An organizational question: what's the difference between files under "Mesh" and files under "Contrib"?

**Comment by AdaRadius** [comment]
Re my just previous comment - I'm having problems reconciling hands worked on under different versions of the Avastar rig - I'll figure it out, but it would be easier if I had a clue on which file was worked on when.

**Comment by aiaustin** [comment]
Mesh should JUST be the files in the releases/release candidates Ada.  Contrib is by developer name and is what indviduals put in.  Some of those might then have been selected to COPY across to the release area.  Serie might be able to explain it better.

**Comment by aiaustin** [comment]
Serie.. I see why Ada will be confused.  Sundance Haiku has placed some more files under Mesh that should be moved to Contrib/Sundance Haiku. Can you do that?

**Comment by AdaRadius** [comment]
Thank you, Ai & Serie!  I'm on the right track then, identifying which mesh bits came from which files in a text editor, lol, and with Serie's help I have a shot at getting the best bits pulled together and people can follow my work, I hope. 
Even if it's a perilous journey, ending, in today's adventure, in Frankenstein claws instead of hands...nicely UV mapped claws at least.

**Comment by Outworldz** [comment]
AdaRadius, you can get the history of any file by using 'gitk filename' from a git window.   Also, the git GUI will show you each commit, in each commit is a list of files.  May not be of much help, but you can at least see if there are any notes and what they did for each commit.

You can also switch to any version by "git checkout hash" where hash is the first dozen or so numbers in the git commit hash number.

**Comment by seriesumei** [comment]
I will do that Austin.

Ada, the idea is that we each are free to put whatever under contrib under our own names.  The rest of the repo should represent the current state of the release, i.e. it doesn't have to be finished, just what the team has decided is being readied for a release.  I would expect the bits you are doing now, combining a lot of separate work and improving it, to basically go there right away.

**Comment by AdaRadius** [comment]
Thank you Fred! I see that da Git has improved the interface enough that I'm close to being able to navigate and maybe be more useful.

**Comment by Outworldz** [comment]
I have asked Robin Wood for permission to include her templates. It might help for more of us to politely ask.

https://www.robinwood.com/Catalog/Technical/SL-Tuts/SLPages/AVUVTemplates.html

chat @ robinwood.com

I am a member of the Roth & Ruth Project at https://github.com/RuthAndRoth/
We just realized that your skins require permission to post elsewhere.
Is it okay for us to put them there with credits? Roth and Ruth are the first Open Source Full Perm Bento Avatars and we would love to include them as we use them constantly.

**Comment by AdaRadius** [comment]
Thank you Fred! I'll take the Robin Wood templates out of the file before I upload it if she doesn't want them here. I have seen her templates in the wild with her name and copyright notice removed from the image - we can do what we can do to be respectful of her work. They may be in other blend files at this GitHub.  

I had a calm conversation with Ilan Tochner yesterday, and will take down any Ruth boxes on any Kitely worlds where I have rights. Any AGPL licensed stuff on Kitely that he doesn't know about, he isn't going to go looking for it.

Maybe a friendly nonprofit with some long-term sustainability would be willing to host an OS sim on one of its servers for Ruth and Roth distribution boxes - I'll find out. 

For the record, any work I do on Ruth or Roth can be under any licensing you want, as long as I don't have to read the license language again.  I'm doing this for the same reason as Shin - a teaching and learning project.

**Comment by Outworldz** [comment]
From Robin Wood:

Yes, you have my permission to post the templates wherever you’d like to post them. :D

I hope you are having a wonderful day!

Take care,

Robin

**Comment by AdaRadius** [comment]
I have a blend file, dae file with all four pieces (body and 3 sets of feet) and UV maps to upload so people can take a look at the vertex weights. I see that GitHub may be easier than last time I tried this, which may be good as last year I couldn't figure it out at all. Doin' the idiot/savant thing, I know. 

After that's figured out, I'll redesign the alpha cuts (from Sundance's and my ideas) and upload that blend file and the dae. 

Then on to Roth.

**Comment by AdaRadius** [comment]
Hokay. When I click Upload, to try to upload files to the Ada Radius directory, I get 'Uploads are disabled. File uploads require push access to this repository'.

What does 'push access' mean and how can I get whatever that is?

**Comment by seriesumei** [comment]
Ada, I gave you write access to the repo now, you should be able to upload files, let me know if that worked.

**Comment by AdaRadius** [comment]
No, I'm still getting the same error message.

**Comment by AdaRadius** [comment]
![Uploads disabled](https://user-images.githubusercontent.com/28539799/55685566-c02a7b80-590c-11e9-85c7-709010eebcaa.png)

**Comment by AdaRadius** [comment]
AHA got the invitation, I should remember to look at all of my emails first. THANK YOU

**Comment by aiaustin** [comment]
A suggestion... that we place ALL the textures used in Ruth 2.0 and Roth 2.0 in a separate in world release box, rather like the R2 Extras. Maybe "R2 Resources".  To encourage in world copies of the same textures where they are needed... hence maintaining their single unique UUID.  Different in SL and OpenSim but hopefully propagated across all OpenSim grids the resources and mesh bodies are used on.

**Comment by AdaRadius** [comment]
OK - grid owner should set up a scripted box that allows people with rez rights to drop textures in? Or? (I was having problems getting some scripts to work - hover scripts - last night, and assumed it was because only the owner has true god rights)

I found that I was able to use textures on RuthAndRoth sim, even if I uploaded them in Kitely grid, but I'm not sure if I can drop them into a box. Worth trying :)

**Comment by aiaustin** [comment]
Nothing that complicated. Lets put all necessary textures on Github and then make a box when RC#4 is created.

Scripting should  work with permissions you have.

**Comment by AdaRadius** [comment]
OK. I think everything I'm using or have used is on GitHub.

**Comment by AdaRadius** [comment]
RC#4.1 is up. I may have to do a Ruthie version with a good UV map and skin, NOT THE SL MAP. I want to be done with working with something that was awful in 2005 and beyond appalling now.

**Comment by AdaRadius** [comment]
I uploaded alpha cuts files and export notes and the dae. GitHub wouldn't let me upload the blend file. I'm still working on the bake textures - fixing RGB and adding wireframe to the texture. Soon, today I hope.

**Comment by AdaRadius** [comment]
and ratsbats I already found an error in the Alpha Cuts coloring, while working on the textures. I'll fix and re-upload. Can I copy over files in the upload?

**Comment by Deledrius** [comment]
> Can I copy over files in the upload?

Replacing a file with a newer revision is a key feature of git. :)

**Comment by AdaRadius** [comment]
Thank you!!

**Comment by Deledrius** [comment]
Thank you (and the whole team) for working to keep this project alive and moving forward. 😺

**Comment by AdaRadius** [comment]
I love it that team members can come and go and the project lives.

**Comment by AdaRadius** [comment]
Sorry for my continued ignorance on GitHub, my learning curve is slow when I have to sort through left-right issues. Though the problem with Git is more the terminology, I think. I am confused by the issue for the Robin Wood templates - I thought I was responding, then realized that someone "closed the issue"  and maybe I "forked it"?  
Questions: I have the original Robin Wood psd files, that she issued years ago. The psd files have the template layers, very useful for when I only want components of the templates. I also have the original Linden Lab UV maps for the various deforms, there are a whole lot of them. @Ai Austin was asking about male and female versions, which do exist for the LL versions but don't for the Robin Wood templates.  I used both the PSD versions of Robin's templates, and occasionally the LL templates. I don't remember which versions, or whether I packed the images into the Blender files. Should I upload them? If so where, and do I have permission to do so?

**Comment by seriesumei** [comment]
Ada, don't worry about the Github stuff, that is exactly how I feel about Blender!  :).  Upload the template PSD files to your directory and I will move them to a similar place like the CMFF templates.

I have noticed that some of the reference files mentioned in various places have disappeared, if you think there is something we should ensure is available for us in the future and the license allows it I am OK with adding it.  Or maybe we should make a new repo for reference things? I don't know how people feel about making the repo larger with multiple PSD/PNG/etc files for reference?

**Comment by aiaustin** [comment]
I put the PSD and PSD(CS2) images (as zipped) files into Contrib/Robin Wood and changed the Readme.txt. Feel free to move where appropriate.  Sources from https://www.robinwood.com/Catalog/Technical/SL-Tuts/SLPages/AVUVTemplates.html

**Comment by AdaRadius** [comment]
I uploaded a whole lot of stuff and left the two blend files in the public folder of my Dropbox account, at least for now. Does anyone know why I was able to upload them a few days ago, and now there's a 25MB cap? Some of my drafts could be removed, but I haven't figured out how to do it.  

Anyway - Alphacuts are drafted, and an export model, I hope free from errors, is ready to upload inworld. If I can tomorrow, I'll look at it inworld and see how the faces did this time. Is there a script that would take names from a notecard and assign them sequentially to rename components of a linkset? :)

**Comment by Deledrius** [comment]
According to this page (https://help.github.com/en/articles/adding-a-file-to-a-repository) there's a 25MB limit only for uploads done through the browser interface.  As long as you make and push the commit through git instead of the website it should work fine.  What client are you using to manage your local repository?

**Comment by aiaustin** [comment]
If you have any problem Ada just let us know and one of us can put the files in place where you want. 

For the two .blend files give me the Dropbox URL and where you want them to be placed and I will copy them over fir you if you wish.

I mostly use Github desktop which makes adding (and subtracting/deleting) any content very easy.  But occasionally I use the web interface to make simple changes such as in text readme files.

**Comment by AdaRadius** [comment]
Thank you Deledrius, I've been using the browser. Fred sent me tutorial sites some time ago; I'll take another whack at it. 

Thank you Ai - if I have figured this out right (first time sharing files at Dropbox since I moved my stuff from from Google; I'm still at the "click on what, where?" phase, lol) the files are here: 
https://www.dropbox.com/s/vo837lmc3jxh85j/Ruth2.0_RC4.2AlphaCuts.blend?dl=0
https://www.dropbox.com/s/js7s2m2cg996du7/Ruth2.0_RC4.4Export.blend?dl=0

I really can't make these files smaller - they're as clean as I can get them and still have the data needed. 

There was a 4.3 blender file for a while - I was making the inworld colormap texture by baking from the model in blender, until I figured out that it was much faster to drag the RGB values into Materials Settings and generate UV maps in color from the 4.2AlphaCuts file, then fix up in Photoshop.

**Comment by seriesumei** [comment]
I download those files and tried to push them in directly, Ruth2.0_RC4.2AlphaCuts.blend is 107MB according to GH and over their hard 100MB limit.  We need to sort out large file support (LFS), I'll do that soon unless someone already knows about it.

**Comment by AdaRadius** [comment]
100MB? I could try putting some of the resources into a separate file, to be appended then deleted. Or linking blend files - editing in one file changes the linked asset in another file. Or splitting out the models I used to make the new UV files. It's only over 7MB. Let me think about how to do that, and I'll reupload in the morning if I'm successful.

**Comment by AdaRadius** [comment]
Did it, barely, lol. I wanted to make sure everything was in each file that anyone might need to follow on, and I might have trimmed back the materials list on Sundance's models too much. The think said I was only removing unused slots, but I don't trust it. 
The new links are:
https://www.dropbox.com/s/s0khde2i0yxdjj4/Ruth2.0_RC%234.3UpdateUVMaps.blend?dl=0
https://www.dropbox.com/s/h6buisab5fbbrju/Ruth2.0_RC4.2AlphaCuts.blend?dl=0
https://www.dropbox.com/s/js7s2m2cg996du7/Ruth2.0_RC4.4Export.blend?dl=0

**Comment by seriesumei** [comment]
Got them!  Thank you Ada, LFS isn't going to be a fun thing if we need it...

**Comment by LucierdaSolari** [comment]
I would like to be able to flatten the nipples on the breasts as well as the vagina on the Ruth mesh.  I am a PG-13 person at most.

**Comment by Deledrius** [comment]
> 
> 
> I would like to be able to flatten the nipples on the breasts as well as the vagina on the Ruth mesh. I am a PG-13 person at most.

That's pretty simple to do in a way that shouldn't affect much of anything.

**Comment by AdaRadius** [comment]
@LucierdaSolari  I've gotten quite a few requests for flattening nipples and groin in both Ruth and Roth - there was much debate at, I think, a Kitely meeting about a year ago. Some love Shin's nipple design, some don't. So I agreed to make two versions when I do the Blender 2.8 versions. Meanwhile, anyone who wants to do it in the current Blender versions will be much appreciated. :)

**Comment by seriesumei** [comment]
Closing this as much has changed, however the ideas about enhancements to the mesh should not get lost, I opened a new issue (https://github.com/RuthAndRoth/Ruth/issues/38) with these specifically as the topic.
