### ISSUE TITLE
Uploading Mesh to Second Life - Check Which Viewer Version to Use

### ISSUE THREAD

**Issue by aiaustin** [RuthAndRoth/Ruth#27]
If, like me, you typically use a single viewer for both SL and OpenSim (Firestorm in my case) lets be aware that the Firestorm viewer folks indicate that the SL+OS version of the viewer should NOT be used to upload meshes to SL.. presumably because the havok physics handling is different.

See the download page at, for example, https://www.firestormviewer.org/windows/ ...

> SL and OpenSim Viewers
> Only needed if you visit OpenSim grids; should not be used for uploading mesh to Second Life.

Possibly this is only related to meshes with mesh physics shapes.

**Comment by fhendrickson** [comment]
I can actually confirm this is the correct assumption.

The only real difference in Firestorm (Secondlife version) and the Firestorm (OpenSim version) other the way it is built is due to the Havok license that LL has with the developers of the Havok physics engine.  Otherwise, the OpenSim version of firestorm works just like normal in Secondlife.
